version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
        aliases:
          - legacywebshop

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
      local_dev_net:
        aliases:
          - web-shop-db-image
  usermanagement:
    build:
      context: ./usermanagement
      dockerfile: Dockerfile
    depends_on:
      - web-shop-db-image
    ports:
      - "8080:8080"
    networks:
      local_dev_net:
        aliases:
          - usermanagement

  productmanagement:
    build:
      context: ./productmanagement
      dockerfile: Dockerfile
    depends_on:
      - web-shop-db-image
      - categorymanagement
    ports:
      - "8081:8081"
    networks:
      local_dev_net:
        aliases:
          - productmanagement

  categorymanagement:
    build:
      context: ./categorymanagement
      dockerfile: Dockerfile
    depends_on:
      - web-shop-db-image
    ports:
      - "8082:8082"
    networks:
      local_dev_net:
        aliases:
          - categorymanagement

networks:
  local_dev_net:
    driver: bridge
